### ISSUE TITLE
Uncaught TypeError: lib.react is not a function

### ISSUE THREAD

**Issue by 0xPiyush** [m93a/svelte-plotly.js#6]
When running the example code from readme Plot is not displayed and this error shows up in the console:
![image](https://user-images.githubusercontent.com/47710035/198128642-0cb08679-089d-4b81-ae8f-382f37c9384a.png)
I am using Svelte version 3.49.0 (not sveltekit) with vite

**Comment by cshaa** [comment]
Hey, Piyush!
Thanks for reporting this. The readme wasn't particularly clear on this, but you also need to install a Plotly distribution – `plotly.js-dist` is a peer dependency of this package, but you can install a different distribution of Plotly, too. I've added detailed instructions about this to the readme. Please check it out and let me know if it solved your issue!

**Comment by 0xPiyush** [comment]
Hello, sorry for the late response.
I tested it again and it still fails with same error
<br>
![image](https://user-images.githubusercontent.com/47710035/205334178-e603e7ac-5983-421a-b0ef-a68136ef352d.png)
Here's my package.json, you can see I did install plotly.js-dist this time.
```
{
  "name": "plotly-test",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "devDependencies": {
    "@sveltejs/vite-plugin-svelte": "^1.1.0",
    "svelte": "^3.52.0",
    "vite": "^3.2.3"
  },
  "dependencies": {
    "plotly.js-dist": "^2.16.3",
    "svelte-plotly.js": "^0.3.0"
  }
}
```

**Comment by cshaa** [comment]
You're right, Vite behaves weirdly with `await import(...)` of CJS modules. I've tried to make the importing more resilient. Could you try version v0.3.2 (published on NPM) and tell me if the problem still persists? Thanks!

**Comment by 0xPiyush** [comment]
I just tried v0.3.2 and it appears to have fixed the issue, thanks a lot!

**Comment by cshaa** [comment]
Awesome! Thanks for reporting the issue!
